CREATE TABLE "user"
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(20)                              NOT NULL,
    password     VARCHAR(255)                             NOT NULL,
    email        VARCHAR(255)                             NOT NULL,
    phone_number VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

DROP TABLE user_data CASCADE;