CREATE TABLE outbox_record
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value   VARCHAR(255),
    user_id INTEGER                                 NOT NULL,
    CONSTRAINT pk_outbox_record PRIMARY KEY (id)
);
ALTER TABLE outbox_record
    ADD CONSTRAINT fk_outbox_user FOREIGN KEY (user_id) REFERENCES "user" (id);